#!/usr/bin/python

# Modified by Dov Grobgeld to get all the files created today.

# python-gphoto2 - Python interface to libgphoto2
# http://github.com/jim-easterbrook/python-gphoto2
# Copyright (C) 2014-19  Jim Easterbrook  jim@jim-easterbrook.me.uk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# "object oriented" version of list-files.py

import dateparser
from datetime import datetime
import logging
import os
import sys
import pdb
import gphoto2 as gp
from pathlib import Path
import signal
import getpass
import shutil
import filecmp

import logging
import sys

# ANSI escape codes for colors
COLOR_RESET = '\033[0m'
COLOR_INFO = '\033[36m'   # Cyan
COLOR_ERROR = '\033[31m'  # Red

class ColorFormatter(logging.Formatter):
    def format(self, record):
        levelname = record.levelname
        if levelname == 'INFO':
            record.levelname = f"{COLOR_INFO}{levelname}{COLOR_RESET}"
        elif levelname == 'ERROR':
            record.levelname = f"{COLOR_ERROR}{levelname}{COLOR_RESET}"
        return super().format(record)

def die(msg):
  sys.stderr.write(msg)
  exit(-1)

def list_files_usb(root_path):
  result = []
  for root, dirs, files in os.walk(root_path):
    for name in files:
      full_path = os.path.join(root, name)
      result.append(full_path)
  return result

def get_file_info_usb(path):
  stat = os.stat(path)
  return stat.st_mtime, stat.st_size

def list_files(camera, path='/'):
  result = []
  # get files
  for name, value in camera.folder_list_files(path):
    result.append(os.path.join(path, name))
  # read folders
  folders = []
  for name, value in camera.folder_list_folders(path):
    folders.append(name)
  # recurse over subfolders
  for name in folders:
    result.extend(list_files(camera, os.path.join(path, name)))
  return result

def get_file_info(camera, path):
  folder, name = os.path.split(path)
  return camera.file_get_info(folder, name)

def get_file_date(camera, path):
  info = get_file_info(camera, path)
  return datetime.fromtimestamp(info.file.mtime)

def get_num_files_from(camera, files, from_date=datetime.now()):
  '''Get the first index of a file today'''
  idx = len(files)-1
  while idx>0:
    dt = get_file_date(camera,files[idx])
    if dt < from_date:
      return idx+1
    idx-=1
  return 0

def get_files_from(camera, files, from_date=datetime.now()):
  '''Get a list of all the files from the given date'''
  result = []
  for f in files:
    info = get_file_info(camera, f)
    dt = datetime.fromtimestamp(info.file.mtime)
    if dt >= from_date:
      result.append((f, info))
  return result

def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)

def is_same_file(entry, local_path, use_sdcard):
    if not os.path.exists(local_path):
        return False
    
    local_size = os.path.getsize(local_path)
    if entry['size'] != local_size:
        return False
    
    if use_sdcard:
        # For SD card, we can do a more robust check
        return filecmp.cmp(entry['path'], local_path, shallow=True)
    else:
        # For camera, compare size and timestamp (assuming we preserved it)
        local_mtime = os.path.getmtime(local_path)
        # Use a small tolerance for float comparison if necessary, but mtime from gp is int
        return abs(entry['mtime'] - local_mtime) < 1

def main():
    from_date = dateparser.parse('2021-08-21 07:00')

    argp = 1
    get_types = []
    use_sdcard = False
    while argp<len(sys.argv) and sys.argv[argp][0]=='-':
      S_ = sys.argv[argp]
      argp+=1

      if S_=='--help':
        print('get_photos_today - Get photos from a date\n'
              '\n'
              'Syntax:\n'
              '  get_photos_today [--jpeg] [--mpeg] [--mov] [--raw] [--sdcard] DATE'
              )
        exit(0)
      if S_=='--jpeg':
        get_types += ['jpeg']
        continue
      if S_=='--mpeg':
        get_types += ['mpeg']
        continue
      if S_=='--mov':
        get_types += ['mov']
        continue
      if S_=='--raw':
        get_types += ['raw']
        continue
      if S_=='--sdcard':
        use_sdcard = True
        continue

      die(f'Unknown option "{S_}"!')
  
    signal.signal(signal.SIGINT, signal_handler)
    
    logging.basicConfig(filename='get_photos_today.log', level=logging.INFO)
    log_formatter = logging.Formatter('%(levelname)s: %(name)s: %(message)s')
    root_logger = logging.getLogger()

    # Create handler for stdout
    handler = logging.StreamHandler(sys.stdout)
    formatter = ColorFormatter('[%(levelname)s] %(message)s')
    handler.setFormatter(formatter)

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(log_formatter)
    formatter = ColorFormatter('[%(levelname)s] %(message)s')
    console_handler.setFormatter(formatter)
    root_logger.addHandler(console_handler)

    logger = logging.getLogger('get_photos_today')
    if argp >= len(sys.argv):
      die('Need date time!')
    from_date = dateparser.parse(sys.argv[argp])
    argp+=1

    logger.info(f'Getting photos from {str(from_date)}')

    files_with_info = [] # List of dictionaries

    if use_sdcard:
      username = getpass.getuser()
      base_path = f'/run/media/{username}'
      if not os.path.exists(base_path):
        die(f'SD card mount base path {base_path} not found!')
      
      mounts = os.listdir(base_path)
      if not mounts:
        die(f'No SD cards found in {base_path}!')
      
      mount_path = os.path.join(base_path, mounts[0])
      logger.info(f'Searching SD card: {mount_path}')
      
      raw_files = list_files_usb(mount_path)
      for f in raw_files:
        mtime, size = get_file_info_usb(f)
        if datetime.fromtimestamp(mtime) >= from_date:
          fname = Path(f).name
          ftype = ''
          if fname.lower().endswith(('.jpg', '.jpeg')): ftype = 'image/jpeg'
          elif fname.lower().endswith(('.mp4', '.mov')): ftype = 'video/mp4'
          files_with_info.append({'path': f, 'mtime': mtime, 'size': size, 'type': ftype, 'folder': str(Path(f).parent), 'name': fname})
    else:
      callback_obj = gp.check_result(gp.use_python_logging())
      camera = gp.Camera()
      try:
          camera.init()
      except gp.GPhoto2Error as ex:
          if ex.code == gp.GP_ERROR_MODEL_NOT_FOUND:
              die('No camera detected!\n')
          raise ex

      raw_files = list_files(camera)
      logger.info(f'There are {len(raw_files)} files on the camera')
      
      for f in raw_files:
        info = get_file_info(camera, f)
        mtime = info.file.mtime
        if datetime.fromtimestamp(mtime) >= from_date:
          folder, name = os.path.split(f)
          files_with_info.append({'path': f, 'mtime': mtime, 'size': info.file.size, 'type': getattr(info.file, 'type', ''), 'folder': folder, 'name': name})
      gp.gp_camera_exit(camera)

    num_errors = 0
    failed_filenames = []
    for idx, entry in enumerate(files_with_info):
      name = entry['name']
      folder = entry['folder']
      ftype = entry['type']
      mtime = entry['mtime']
      fpath = entry['path']
      
      is_mov_format = (ftype == 'video/mp4')

      if not (len(get_types)==0
          or ('jpeg' in get_types and 'jp' in name.lower())
          or ('mpeg' in get_types and 'mp' in name.lower())
          or ('raw' in get_types and 'cr3' in name.lower())
          or ('mov' in get_types and is_mov_format)):
        continue

      dt = datetime.fromtimestamp(mtime)
      if is_mov_format:
        target_base = dt.strftime('VID_%Y%m%d_%H%M%S.mp4')
      else:
        target_base = name

      target_name = target_base
      skip_file = False
      
      if os.path.exists(target_name):
          if is_same_file(entry, target_name, use_sdcard):
              skip_file = True
          else:
              # Collision found, look for unique name or an existing copy
              path_obj = Path(target_base)
              stem = path_obj.stem
              suffix = path_obj.suffix
              counter = 1
              while True:
                  candidate = f"{stem}_{counter}{suffix}"
                  if not os.path.exists(candidate):
                      target_name = candidate
                      break
                  if is_same_file(entry, candidate, use_sdcard):
                      target_name = candidate
                      skip_file = True
                      break
                  counter += 1

      if skip_file:
          logger.info(f'Skipping {name} (already exists as {target_name})')
          continue

      logger.info(f'Getting {name} -> {target_name} ({idx+1}/{len(files_with_info)}) {str(dt)}')
      
      try:
        if use_sdcard:
          shutil.copy2(fpath, target_name)
        else:
          camera = gp.Camera()
          camera.init()
          camera_file = gp.check_result(gp.gp_camera_file_get(
              camera, str(folder), str(name), gp.GP_FILE_TYPE_NORMAL))
          file_data = gp.check_result(gp.gp_file_get_data_and_size(camera_file))
          if len(file_data) == 0:
            raise Exception('Got empty file!')
          with open(target_name,'wb') as fh:
            data = memoryview(file_data)
            fh.write(data)
          # Preserve timestamp
          os.utime(target_name, (mtime, mtime))
          camera.exit()
      except Exception as e:
        logger.error(f'Failed getting file {name}: {e}')
        failed_filenames += [name]
        num_errors += 1

    if num_errors>0:
      logger.error(f'Failed getting {num_errors} files! Try copying the following files manually:\n  ' + '\n  '.join(failed_filenames))

    return 0

if __name__ == "__main__":
    sys.exit(main())
